# Generated by Django 5.2.1 on 2025-05-27 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_genre_book_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='user',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
