# Generated by Django 5.2.1 on 2025-05-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_rename_genre_book_genres'),
        ('catalog', '0003_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='catalog.author'),
        ),
    ]
