# Generated by Django 5.2.1 on 2025-05-27 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='authors',
        ),
    ]
