# Generated by Django 5.2.1 on 2025-05-27 08:17

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_rename_author_book_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to=book.models.book_image_file_path),
        ),
    ]
