# Generated by Django 5.2.1 on 2025-05-27 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='user',
        ),
    ]
